In [4]:
import numpy as np
import pandas as pd
from numpy.linalg import matrix_rank
from numpy.linalg import inv

# Even determined system
X = np.array([[1, 1], [3, 4]])
y = np.array([[0], [1]])
w = inv(X) @ y
print(w)
print(np.linalg.det(X))
print(matrix_rank(X))

[[-1.]
 [ 1.]]
0.9999999999999998
2


In [ ]:
import numpy as np
import pandas as pd
from numpy.linalg import matrix_rank
from numpy.linalg import inv

# Over determined system
X = np.array([[1, 2], [2, 4], [1, -1]])
y = np.array([[0], [0.1], [1]])
w = inv(X.T @ X) @ X.T @ y
print(w)

In [ ]:
import numpy as np
import pandas as pd
from numpy.linalg import matrix_rank
from numpy.linalg import inv

# Under determined system
X = np.array([[1, 0, 1, 0], [1, -1, 1, -1], [1, 1, 0, 0]])
y = np.array([[1],[0], [1]])
w = X.T @ inv(X@ X.T) @ y
print(w)

In [ ]:
import numpy as np
import pandas as pd
from numpy.linalg import matrix_rank
from numpy.linalg import inv

# Even determined system with transpose
X = np.array([[1, 2], [3, 6]])
yT = np.array([[0, 1]])
print(matrix_rank(X)) #2 x 2 matrix with rank 1 is not invertible thus no solution

In [11]:
import numpy as np
import pandas as pd
from numpy.linalg import matrix_rank
from numpy.linalg import inv

# Under determined system with transpose
X = np.array([[1, 2], [2, 4], [1, -1]])
y = np.array([[0], [1]])
yT = y.T
wT = yT @ inv(X.T @ X) @ X.T
print(wT.T)
# Alternative method for Under determined system with transpose
X = np.array([[1, 2], [2, 4], [1, -1]])
y = np.array([[0], [1]])
w = X @ inv(X.T @ X) @ y
print(w)

[[ 0.06666667]
 [ 0.13333333]
 [-0.33333333]]
[[ 0.06666667]
 [ 0.13333333]
 [-0.33333333]]


In [ ]:
import numpy as np
import pandas as pd
from numpy.linalg import matrix_rank
from numpy.linalg import inv

# Linear regression of over determined system
X = np.array([[1, -10], [1, -8], [1, -3], [1, -1], [1, 2], [1, 8]]) #with bias
Y = np.array([[5], [5], [4], [3], [2], [2]])
w = inv(X.T @ X) @ X.T @ Y
print(w)
X = np.array([[-10], [-8], [-3], [-1], [2], [8]]) #without bias
w = inv(X.T @ X) @ X.T @ Y
print(w)

In [ ]:
import numpy as np
import pandas as pd
from numpy.linalg import matrix_rank
from numpy.linalg import inv

# Linear regression of under determined system
X = np.array([[ 1, 0, 1], [2, -1, 1], [1, 1, 5]]) #without bias
y = np.array([[1], [2], [3]])
w = inv(X) @ y
print([[-1, 2, 8]] @ w)
print([[1, 5, -1]] @ w)
X = np.array([[1, 1, 0, 1], [1, 2, -1, 1], [1, 1, 1, 5]]) #with bias
w = X.T @ inv(X@ X.T) @ y
print([[1, -1, 2, 8]] @ w)
print([[1, 1, 5, -1]] @ w)

In [ ]:
import pandas as pd
import numpy as np
from numpy.linalg import inv

# Linear regression with multiple outputs and over determined system
X = np.array([[1, 3, -1, 0], [1, 5, 1, 2], [1, 9, -1, 3], [1, -6, 7, 2], [1, 3, -2, 0]])
y = np.array([[1, -1], [-1, 0], [1, 2], [0, 3], [1, -2]])
w = inv(X.T @ X) @ X.T @ y
print(w)
print([[1, 8, 0, 2]] @ w)

In [16]:
import pandas as pd
import numpy as np
from numpy.linalg import inv
from numpy.linalg import matrix_rank
from sklearn.metrics import mean_squared_error

X = np.array([[1, 4, 2], [-3, 10, 5]])
print(matrix_rank(X))
X = np.array([[1, 50, 10], [1, 40, 7], [1, 65, 12], [1, 70, 5], [1, 75, 4]])
y = np.array([[9, 3], [6, 7], [5, 6], [3, 1], [2, 9]])
w = inv(X.T @ X) @ X.T @ y

2


In [10]:
import numpy as np
import pandas as pd
from numpy.linalg import inv
from sklearn.preprocessing import PolynomialFeatures

# Polynomial regression without ridge of overdetermined system (primal form)
X = np.array([[-10], [-8], [-3], [-1], [2], [8]])
y = np.array([[5], [5], [4], [3], [2], [2]])
order = 3
poly = PolynomialFeatures(order)
P = poly.fit_transform(X)
w_dual = inv(P.T @ P) @ P.T @ y
Xnew = np.array([[9]])
Pnew = poly.fit_transform(Xnew)
Ynew= Pnew @ w_dual
print(Ynew)

[[2.46609771]]


In [13]:
import numpy as np
import pandas as pd
from numpy.linalg import inv
from sklearn.preprocessing import PolynomialFeatures

# Polynomial regression without ridge of underdetermined system (primal form)
X = np.array([[1, 0, 1], [1, -1, 1]])
y = np.array([[0], [1]])
order = 3
poly = PolynomialFeatures(order)
P = poly.fit_transform(X)
w_dual = P.T @ inv(P @ P.T) @ y
print(w_dual)

[[ 0. ]
 [ 0. ]
 [-0.1]
 [ 0. ]
 [ 0. ]
 [-0.1]
 [ 0. ]
 [ 0.1]
 [-0.1]
 [ 0. ]
 [ 0. ]
 [-0.1]
 [ 0. ]
 [ 0.1]
 [-0.1]
 [ 0. ]
 [-0.1]
 [ 0.1]
 [-0.1]
 [ 0. ]]


In [7]:
import numpy as np
import pandas as pd
from numpy.linalg import inv
from sklearn.preprocessing import PolynomialFeatures

# Polynomial regression with ridge (primal and dual)
X = np.array([[0, 0], [1, 1], [1, 0], [0, 1]])
y = np.array([[-1], [-1], [1], [1]])
order = 2
poly = PolynomialFeatures(order)
P = poly.fit_transform(X)
if(P.shape[0] > P.shape[1]): # Overdetermined
    reg_L = 0.0001 * np.identity(P.shape[1]) # Regularization term
    w_dual = inv(P.T @ P + reg_L) @ P.T @ y # Primal form for overdetermined system
else: # Underdetermined
    reg_L = 0.0001 * np.identity(P.shape[0]) # Regularization term
    w_dual = P.T @ inv(P @ P.T + reg_L) @ y # Dual form for underdetermined system
Xnew = np.array([[0.1, 0.1], [0.9, 0.9], [0.1, 0.9], [0.9, 0.1]])
Pnew = poly.fit_transform(Xnew)
Ynew = Pnew @ w_dual
print(Ynew)

[[-0.81941134]
 [-0.81965119]
 [ 0.45979711]
 [ 0.45979711]]


In [15]:
import numpy as np
import pandas as pd
from numpy.linalg import inv

# Binary classification (+1 for class 1, -1 for class 2) with linear regression
X = np.array([[1, -1], [1, 0], [1, 0.5], [1, 0.3], [1, 0.8]])
y = np.array([[1], [1], [-1], [1], [-1]])
w = inv(X.T @ X) @ X.T @ y
print([[1, -0.1], [1, 0.4]] @ w)

[[ 0.44444444]
 [-0.11111111]]


In [16]:
import numpy as np
import pandas as pd
from numpy.linalg import inv

# Multi-category classification (One hot encoding) with linear regression
X = np.array([[1, -1], [1, 0], [1, 0.5], [1, 0.3], [1, 0.8]])
y = np.array([[1, 0, 0], [1, 0, 0], [0 , 1, 0], [0, 0, 1], [0, 1, 0]])
w = inv(X.T @ X) @ X.T @ y
print([[1, -0.1], [1, 0.4]] @ w)

[[0.54297694 0.27777778 0.17924528]
 [0.21802935 0.55555556 0.22641509]]


In [32]:
import numpy as np

# Correlation coefficient
x1 = np.array([3.3459, 1.0893, 3.2103, 1.7440, 1.6762])
x2 = np.array([2.7435, 2.9113, 1.4706, 1.2895, 2.1366])
x3 = np.array([-1.7253, -0.7804, -0.9944, 0.5307, -1.0502])
y = np.array([2.9972, 1.1399, 2.2280, 0.3387, 2.5042])
r = np.corrcoef(x1, y)
print(np.corrcoef(x1, y)[0][1])
print(np.corrcoef(x2, y)[0][1])
print(np.corrcoef(x3, y)[0][1])

0.6509901032456192
0.37221827010441094
-0.930813148104117


In [6]:
import numpy as np
import pandas as pd
import math

# Gradient descent algorithm
a_out = []
f1_out = []
a = 1.5
for i in range(0, 5):
    gradient = 5 * (a ** 4)
    a = a - gradient * 0.1 
    a_out.append(a)
    f1_out.append(a ** 5)
print(a_out)
print(f1_out)

[-1.03125, -1.5967411994934082, -4.846926554971105, -280.8003334098373, -3108569059.6045403]
[-1.1663255989551544, -10.379409726162732, -2675.0517912391933, -1745774299031.264, -2.9027029896735814e+47]


In [38]:
import numpy as np

# MSE of Regression tree at root and depth 1
x = np.array([0.2, 0.7, 1.8, 2.2, 3.7, 4.1, 4.5, 5.1, 6.3, 7.4])
y = np.array([2.1, 1.5, 5.8, 6.1, 9.1, 9.5, 9.8, 12.7, 13.8, 15.9])
mean_y = np.mean(y)

# Calculate squared differences and average to get MSE at the root
mse_root = np.mean((y - mean_y)**2)
print(mse_root)
# print(f'MSE at the root: {mse_root:.3f}')

# Decision threshold
threshold = 3

# Separate data into left and right branches
y_left = y[x < threshold]
y_right = y[x >= threshold]

# Calculate mean of y for left and right branches
mean_y_left = np.mean(y_left)
mean_y_right = np.mean(y_right)

# Calculate squared differences and average for left and right branches
mse_left = np.mean((y_left - mean_y_left)**2)
mse_right = np.mean((y_right - mean_y_right)**2)

# Calculate overall MSE at depth 1
overall_mse_depth_1 = (len(y_left) * mse_left + len(y_right) * mse_right) / len(y)

print(overall_mse_depth_1)
#print(f'Overall MSE at depth 1: {overall_mse_depth_1:.3f}')

20.6381
5.56475
